name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        git submodule update --init --recursive
        mkdir -p test/build
        cd test/build
        cmake ..
        make
        ./mcfile-test
