name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: test
      run: |
        mkdir -p test/build
        cd test/build
        cmake ..
        make
        ./mcfile-test
    - name: example
      run: |
        mkdir -p example/build
        cd example/build
        cmake ..
        make
