name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: mkdir -p test/build && cd test/build && cmake .. && make && ./mcfile-test
