name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: test
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --parallel --target mcfile-test --config Release --verbose
        ./mcfile-test
    - name: example
      run: |
        mkdir -p example/build
        cd example/build
        cmake ../.. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --parallel --target mcfile-example --config Release --verbose
